### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by zstadler** [SafwatHalaby/osm-bot#1]
The /home/osm/openStreetMap/scripts/download.sh script is [referenced by the code](https://github.com/SafwatHalaby/osm-bot/blob/master/gtfs/getAndParse.sh#L19), but it was not included in the source code. It seems the script is specific for downloading the GTFS data.

Alternatively, the script can be replaced with
```
wget --timestamping http://..../israel-public-transportation.zip
```

**Comment by SafwatHalaby** [comment]
The download is FTP and not http, and so  the above replacement would not work. I uploaded the `expect` script here: https://github.com/SafwatHalaby/osm-bot/blob/master/gtfs/download.sh

**Comment by SafwatHalaby** [comment]
According to its manual, wget does support FTP, I overcomplicated this. I will replace the script with a wget one-liner.

**Comment by SafwatHalaby** [comment]
Fixed in https://github.com/SafwatHalaby/osm-bot/commit/8a3aa70bbb528d091324afc400bf7fb0e091572c

**Comment by zstadler** [comment]
You may delete the [gtfs/download.sh](https://github.com/SafwatHalaby/osm-bot/blob/master/gtfs/download.sh) script from the repository as it is no longer in use.
